language: python
python: 3.5
cache: pip
addons:
  postgresql: "9.3"
env:
  - DATABASE=ENGINE=django.db.backends.postgresql_psycopg2:NAME=squad:USER=postgres:PASSWORD=squad:HOST=127.0.0.1:PORT=5432
  - DATABASE=

before_install:
  - psql -d template1 -c 'create extension hstore;' -U postgres
  - psql -c 'create database "squad";' -U postgres

install:
  - pip install -r requirements-dev.txt

script:
  - env
  - python manage.py test --noinput -v 2

notifications:
  email:
    on_success: change
    on_failure: change
  irc:
    on_success: change
    on_failure: change
    channels:
      - "chat.freenode.net#linaro-qa"
