language: python
python:
  - 3.5
cache: pip
addons:
  postgresql: "9.5"
env:
  - TESTENV=travis-postgresql DATABASE=ENGINE=django.db.backends.postgresql_psycopg2:NAME=squad:USER=postgres:PASSWORD=squad:HOST=127.0.0.1:PORT=5432
  - TESTENV=travis-sqlite3 DATABASE=

before_install:
  - if test -n "$DATABASE"; then pip install psycopg2; fi
  - if test -n "$DATABASE"; then psql -d template1 -c 'create extension hstore;' -U postgres; fi
  - if test -n "$DATABASE"; then psql -c 'create database "squad";' -U postgres; fi

install:
  - pip install --upgrade setuptools
  - pip install -r requirements-dev.txt

script:
  - ./scripts/travis

notifications:
  email:
    on_success: change
    on_failure: change
  irc:
    on_success: change
    on_failure: change
    channels:
      - "chat.freenode.net#linaro-qa"
