language: python
python: 3.5
cache: pip
addons:
  postgresql: "9.3"
env:
  - DATABASE=ENGINE=django.db.backends.postgresql_psycopg2:NAME=squad:USER=postgres:PASSWORD=squad:HOST=127.0.0.1:PORT=5432
  - DATABASE=

before_install:
  - psql -d template1 -c 'create extension hstore;' -U postgres
  - psql -c 'create database "squad";' -U postgres

install:
  - pip install -r requirements-dev.txt

script:
  - './manage.py test --noinput -v 2 2>&1 | tee .tests'
  - './scripts/travis-metadata > .metadata.json'
  - 'if [ -z "$DATABASE" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./scripts/dogfood http://squad.puzzle.analizo.org/api linaro-qa/squad; fi'
  - "! grep '^test_.*\\(ERROR\\|FAIL\\)' .tests"

notifications:
  email:
    on_success: change
    on_failure: change
  irc:
    on_success: change
    on_failure: change
    channels:
      - "chat.freenode.net#linaro-qa"
